spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  propertis.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  # url: jdbc:postgresql:{external url @이후 ~ .com포함해서까지}:5432/{db이름}
  url: jdbc:postgresql://dpg-d22g2ge3jp1c738sne5g-a.oregon-postgres.render.com:5432/snsdb_g3f4
  username: snsdb_g3f4_user
  password: hITSIzgrrFItLtJrQNlCK8QaPWIQIAk1
  platform:
  driver-class-name: org.postgresql.Driver


jwt:
  secret-key: fast-campus.sns-application-2022.secret-key
  # 30 days
  token.expired-time-ms: 2592000000


server:
  address: 0.0.0.0
  port: 8080